# Generated by Django 6.0.7 on 2026-07-23 04:20

import apps.reviews.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 rating (secondary to trust score)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_edited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business')),
            ],
            options={
                'db_table': 'vp_review',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/', validators=[apps.reviews.models.validate_evidence_file])),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('document', 'Document'), ('screenshot', 'Screenshot')], db_index=True, max_length=20)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='reviews.review')),
            ],
            options={
                'db_table': 'vp_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_score', models.PositiveSmallIntegerField(default=0)),
                ('reputation_score', models.PositiveSmallIntegerField(default=0)),
                ('community_score', models.PositiveSmallIntegerField(default=0)),
                ('recency_score', models.PositiveSmallIntegerField(default=0)),
                ('engagement_score', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='reviews.review')),
            ],
            options={
                'db_table': 'vp_trust_score',
            },
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('authentic', 'Authentic'), ('suspicious', 'Suspicious'), ('inconclusive', 'Inconclusive')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='reviews.evidence')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vp_evidence_verification',
                'constraints': [models.UniqueConstraint(fields=('evidence', 'verified_by'), name='unique_verification_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', 'is_active', '-created_at'], name='vp_review_busines_fb4ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'is_active'], name='vp_review_author__833be5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='vp_review_rating_c6f6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'business'), name='unique_review_per_user_per_business'),
        ),
    ]
